# ...existing code...

INSTALLED_APPS = [
    # ...existing code...
    'apps.basket.apps.BasketConfig',
    # ...existing code...
] 

OSCAR_SHOP_APPS = [
    'apps.basket.apps.BasketConfig',  # Используем наше собственное приложение корзины
    # ...другие приложения Oscar...
]

# ...existing code...
