# Generated by Django 4.2.17 on 2025-01-04 22:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_remove_attributeoption_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributeoption',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='attributeoption',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attributeoption',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Price'),
        ),
    ]
